//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.catfeed.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import com.catfeed.R.layout;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.googlecode.flickrjandroid.photos.Photo;

public final class SubscriptionsActivity_
    extends SubscriptionsActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.subscriptions_activity);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static SubscriptionsActivity_.IntentBuilder_ intent(Context context) {
        return new SubscriptionsActivity_.IntentBuilder_(context);
    }

    @Override
    public void updateSubscriptionImage(final Photo photo) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    SubscriptionsActivity_.super.updateSubscriptionImage(photo);
                } catch (RuntimeException e) {
                    Log.e("SubscriptionsActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void fetchFlickrImage(final Context context, final Long id, final String search) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    SubscriptionsActivity_.super.fetchFlickrImage(context, id, search);
                } catch (RuntimeException e) {
                    Log.e("SubscriptionsActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SubscriptionsActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SubscriptionsActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
