//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.catfeed.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.CheckBox;
import android.widget.SeekBar;
import android.widget.SeekBar.OnSeekBarChangeListener;
import android.widget.TextView;
import com.catfeed.CatFeedApp;
import com.catfeed.R.id;
import com.catfeed.R.layout;

public final class SubscriptionEditActivity_
    extends SubscriptionEditActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.subscription_edit);
    }

    private void init_(Bundle savedInstanceState) {
        application = ((CatFeedApp) this.getApplication());
    }

    private void afterSetContentView_() {
        downloadContent = ((CheckBox) findViewById(id.downloadContent));
        retainFor = ((SeekBar) findViewById(id.retainFor));
        downloadImage = ((CheckBox) findViewById(id.downloadImage));
        retainForLabel = ((TextView) findViewById(id.retainForLabel));
        title = ((TextView) findViewById(id.title));
        url = ((TextView) findViewById(id.url));
        {
            View view = findViewById(id.downloadContent);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SubscriptionEditActivity_.this.downloadContent();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.downloadImage);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        SubscriptionEditActivity_.this.downloadImage();
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) findViewById(id.url));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void afterTextChanged(Editable s) {
                        SubscriptionEditActivity_.this.urlAfterTextChanged(view);
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                    }

                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) findViewById(id.title));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void afterTextChanged(Editable s) {
                        SubscriptionEditActivity_.this.titleAfterTextChanged(view);
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                    }

                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                }
                );
            }
        }
        {
            final SeekBar view = ((SeekBar) findViewById(id.retainFor));
            if (view!= null) {
                view.setOnSeekBarChangeListener(new OnSeekBarChangeListener() {


                    @Override
                    public void onStartTrackingTouch(SeekBar seekBar) {
                    }

                    @Override
                    public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                        SubscriptionEditActivity_.this.onProgressChangeOnSeekBar(seekBar, progress, fromUser);
                    }

                    @Override
                    public void onStopTrackingTouch(SeekBar seekBar) {
                    }

                }
                );
            }
        }
        prepopulate();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static SubscriptionEditActivity_.IntentBuilder_ intent(Context context) {
        return new SubscriptionEditActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, SubscriptionEditActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public SubscriptionEditActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
