//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.catfeed;

import com.catfeed.db.Repository_;

public final class CatFeedApp_
    extends CatFeedApp
{


    private void init_() {
        repository = Repository_.getInstance_(this);
        rss = RssFeeder_.getInstance_(this);
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

}
