//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.catfeed;

import android.app.Activity;
import android.content.ContentResolver;
import android.content.Context;
import android.util.Log;
import android.view.View;
import com.catfeed.db.Repository_;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import utils.Progress;

public final class WebPageFeeder_
    extends WebPageFeeder
{

    private Context context_;

    private WebPageFeeder_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        ((Repository_) repository).afterSetContentView_();
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        if (context_ instanceof Activity) {
            activity = ((Activity) context_);
        }
        context = context_;
        repository = Repository_.getInstance_(context_);
    }

    public static WebPageFeeder_ getInstance_(Context context) {
        return new WebPageFeeder_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void download(final ContentResolver content, final Progress refreshing, final String[] urls) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    WebPageFeeder_.super.download(content, refreshing, urls);
                } catch (RuntimeException e) {
                    Log.e("WebPageFeeder_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
